[project]
name = "landmarks_utils"
dynamic = ["version"]
requires-python = ">=3.9"
description = "landmarks_utils is .....  in development"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Clemens Watzenboeck", email = "clemens.watzenboeck@meduniwien.ac.at"},
    { name = "Center for Imaging Research; Medical University of Vienna" }
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
keywords = [
    "deep learning",
    "medical image analysis",
]
dependencies = [
    "nbstripout",
    "torch",
    "torchvision",
    "monai",
    "pydicom",
    "tqdm",
    "dicom2nifti",
    "scipy",
    "numpy",
    "scikit-learn",
    "scikit-image",
    "SimpleITK",
    "pandas",
    "graphviz",
    "requests",
    "nibabel",
    "matplotlib",
    "seaborn",
    "imagecodecs",
    "yacs",
    "einops",
    "pytest",
    "imutils",  # for code of thomas
    #"importlib-metadata"
    "ipython",
    "jupyter", 
    "ipykernel",
    "mlflow",
    "pingouin",
    # "landmarker",
    "optuna", 
#    "rpy2", 
    "openpyxl", 
    "pyqt5",
    "napari>=0.4.3",
    "magicgui>=0.2.5",           
    "dask-image",                 
    "numexpr>=2.8.4"
]

[project.scripts]
landmarks_utils__print_package_infos = "landmarks_utils.tools.print_package_info:main"
landmarks_utils__annotate_landmarks = "landmarks_utils.tools.landmark_annotation:main"
landmarks_utils__annotate_landmarks_prepopulation = "landmarks_utils.tools.landmark_annotation_prepopulation:main"
landmarks_utils__annotate_landmarks_combine_annotations = "landmarks_utils.tools.landmark_annotation_combine_annotations:main"
landmarks_utils__annotate_landmarks_consistency_check = "landmarks_utils.tools.landmark_annotation_check_consistency:main"

[project.optional-dependencies]
dev = [
    "black",
    "ruff",
    "pre-commit"
]
rpackages = [
  # these can’t be installed via pip, but you can document that
  # users should do:
  #   conda install -c conda-forge r-lme4 r-matrix r-reformulas r-psych r-irr
  # or the apt/yum equivalent for Matrix, lme4, etc.
]


[build-system]
requires = ["setuptools>=67.8.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

#[tool.setuptools.packages.find]
#where = ["."]
## include = ["landmarks_utils"]
#exclude = [
#    "docs",
#    "documentation",
#    "logs",
#    "notebooks",
#    "references",
#    "singularity",
#    "slurm",
#    "tests",
#    "tutorials",
#    "data",
#    "features",
#    "inference",
#    "networks",
#    "training",
#    "utils",
#    "visualization", 
#]

[tool.setuptools_scm]
write_to = "landmarks_utils/_version.py"
local_scheme = "node-and-date"

[tool.setuptools.package-data]
"landmarks_utils.resources.patch_extraction" = ["*.json"]
"landmarks_utils.resources.scores_metadata" = ["*.json", "*.yml"]
